### PR TITLE
Include pre-compiled definitions

### PR DESCRIPTION
**Pull request by cipherxof**
This allows us to include the package into our projects without having to run the build script on post install, which is somewhat slow. 

I'm unsure if this is how you wanted the setup to be but I feel it makes using the package more straight forward.

### CODE REVIEW

**Comment by TinkerWorX** [comment]
Can you elaborate a bit on what this solves exactly? Under normal conditions, `postinstall` is only run once, when you install this package, so even if it's slow, it's a one time thing only.

**Comment by cipherxof** [comment]
As far as npm packages go you're generally supposed to include the compiled code. At the very least I think the github repo could omit the dist folder but the npm package should probably include it. If every package forced you to compile during postintall setup would probably take ages.

You can support multiple versions out of the box as well, although that's not particularly useful at the moment unless someone were going to compile 1.27 types for use with NetEase.

**Comment by TinkerWorX** [comment]
I'm fine with pre-compiling it for npm along with adding proper versions, I think that's a good idea, I just have never gotten around to putting it on npm yet because TSTL still didn't have any package support at the time I made this, so it kinda required this hacky approach that would put the generated files in the install folder.

The reason I'm not a fan of adding the pre-compiled definitions to the repo is that they cause huge diffs that we aren't going to be looking at anyways, which can become a source of bugs as someone might update the json files without building or vice versa.

**Comment by cipherxof** [comment]
I agree it could get messy. I suppose it's probably best to leave changes like these to the npm package.

**Comment by TinkerWorX** [comment]
Yeah, what I imagine is we need to put the build in prepublish instead of postinstall, and then whenever you grab it from npm you get pre-compiled definitions, but if you grab from the repo, you have to manually run the build script.

I think the challenge with putting it on npm however is that the pre-compiled files will end up inside node_modules/, which makes it a bit icky to use, but I think that's the best we have at the moment right?

**Comment by cipherxof** [comment]
It shouldn't be a problem if they're in node_modules because they're just typings. We don't have to import them in our code, we can define them in tsconfig.

```ts
"types": [
    "war3-types-strict/1.32.10"
]
```

**Comment by TinkerWorX** [comment]
Ah of course, the issue doesn't come up until we need actual TS source code.

Are you up for updating this PR to instead target prepublish and maybe add a few points to the README on how to publish to npm along with deleting the pre-compiled definitions?

Rest of the changes look fine, I've read you're supposed to version the lock file, but I honestly don't know if that's important in this case, seems to be more in environments where you have a lot of systems relying on exact packages.

**Comment by TinkerWorX** [comment]
Also, if we're publishing to npm, maybe we need an .npmignore file, so we don't include all the other useless stuff.

**Comment by cipherxof** [comment]
Yeah I will try to update it this weekend. 👍

**Comment by cipherxof** [comment]
I updated the the package to build on prepublishOnly. Supporting multiple versions is going to be more complicated and not immediately useful for most people. I suppose we're going to need a base definition file of whatever lowest patch we want to support, then include additional definitions for the changes in each patch similar to how lua-types handles it.

I haven't actually tested the prepublish script because I didn't want to publish/unpublish my own version of the package. I assume it will work as-is.

**Pull request merged**
